### ISSUE TITLE
Error when trying to add a delegate

### ISSUE THREAD

**Issue by fervi** [wise-team/wise-hub#22]
Hello. I wanted to add a delegator, but Wise Hub displays the error:
![obraz](https://user-images.githubusercontent.com/2242925/48906175-f686c300-ee63-11e8-8dad-4194539792a2.png)

This is probably an error in the verification of the nickname, because entering a non-existent nickname displays the correct error.

**Comment by Jblew** [comment]
The error is located somewhere in the RulesetsModule in Vuex store. I have to create some unit tests for this file to locate the error.

**Comment by Jblew** [comment]
Not fixed in a case when user previously had some rulesets and then cleared them.
