### ISSUE TITLE
New user is unable to turn on a daemon

### ISSUE THREAD

**Issue by noisy** [wise-team/wise-hub#26]
The problem: 

### I did:

I created new ruleset and switched to daemon tab

### I expected to see:

![selection_999 598](https://user-images.githubusercontent.com/201263/49194840-f9624600-f384-11e8-9258-35e79fce79d6.png)

### Instead, I saw:

![selection_999 599](https://user-images.githubusercontent.com/201263/49194878-1a2a9b80-f385-11e8-88b9-95b91e7ab86f.png)

### Recording:
https://streamable.com/7q66k

**Comment by bgornicki** [comment]
Same problem here

**Comment by Jblew** [comment]
Could you please check what does the "Developer console" in your browser says? Is there any error?
I am suspicious about user settings loaging i Auth module of frontend store

**Comment by bgornicki** [comment]
![image](https://user-images.githubusercontent.com/4411084/49254179-92a95f00-f44e-11e8-904b-326c88605526.png)

**Comment by Jblew** [comment]
And the line is:
```js
settings(): UserSettings {
    return d(d(s(this.$store).state.auth.user).settings);
},
```

Great! Thank you. That is what I was expecting. End of work for today. Will fix it tomorrow. Thanks!
