### ISSUE TITLE
Dates in History/Recent Activity should be displayed as "X seconds/minutes/hours ago"

### ISSUE THREAD

**Issue by noisy** [wise-team/wise-hub#29]
## The feature:

More user friendly interface, which allows more easily recognize when last time action took place.

![selection_999 611](https://user-images.githubusercontent.com/201263/49281925-1d5d7e80-f48e-11e8-9ba5-9b47166d2dc1.png)

On hover, dates should be still visable in iso 8601 format, like here:
![selection_999 614](https://user-images.githubusercontent.com/201263/49281701-81cc0e00-f48d-11e8-8fa6-8c694ebdfdcf.png)

## It is important for me because:

Without more "human readable" format like "2 minutes ago" it is more difficult to notice that Wise was actually very recently used by other people.

## It is important for steem because:

We want to show to other people that Wise is widely used and this change will boost that perception :)

**Comment by Jblew** [comment]
Done.
