### ISSUE TITLE
Move staging from dev.wise.jblew.pl to staging.wise.vote

### ISSUE THREAD

**Issue by noisy** [wise-team/wise-hub#39]

**Comment by Jblew** [comment]
Staging server: 51.75.160.194, 2001:41d0:801:2000::1d51
Staging vault server: 51.38.133.176, 2001:41d0:0601:1100:0000:0000:0000:24cd

Todo list: 
staging.wise.vote
- [x] A 
- [x] AAAA 

docs.staging.wise.vote
- [x] A 
- [x] AAAA 

sql.staging.wise.vote
- [x] A
- [x] AAAA

hub.staging.wise.vote
- [x] A
- [x] AAAA

test.staging.wise.vote
- [x] A
- [x] AAAA

vault.staging.wise.vote
- [x] A
- [x] AAAA
- [x] HashiVault/config 

Other: 
- [x] Update steemconnect config
- [x] Delete dev.wise.vote domains
- [x] Deploy changes to staging server
- [x] Regenerate letsencrypt certs with certbot

**Comment by Jblew** [comment]
Done. Bonuses from this task:
- finally generated proper CA certs for vault (with proper x509v3 extensions) that can be attached to node instances via NODE_EXTRA_CA_CERTS env
- created deployment instructions for vault servers: https://github.com/wise-team/ansible-playbooks/blob/master/vault-setup/Install%20instructions.md
- put all config files needed to configure vault server in ansible-playbooks repo: https://github.com/wise-team/ansible-playbooks/tree/master/vault-setup
